name: Test Stable Diffusion API

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test-stable-diffusion:
    runs-on: ubuntu-latest  # Use GitHub's cloud environment

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install replicate

      # Step 4: Set environment variables
      - name: Set Replicate API Key
        run: echo "REPLICATE_API_TOKEN=${{ secrets.REPLICATE_API_TOKEN }}" >> $GITHUB_ENV

      # Step 5: Run the test script
      - name: Run image generation test
        run: python test_image_generation.py
